blank_issues_enabled: false
name: Add default message to new issues

on:
  issues:
    types: [opened]

jobs:
  add-branch-name:
    runs-on: ubuntu-latest
    
    steps:
    - name: Add default message to new issues
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const branchName = 'issue-' + context.payload.issue.number;
          const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
          await octokit.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.issue.number,
            body: `Do all work for this task in a branch called ${branchName}.`
          });
